# Notes

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

# librosa
import librosa
import librosa.display

In [2]:
import sys
import os

# Obtener la ruta del directorio raíz
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))

In [3]:
from src.data_engineering import process_features

In [4]:
familias = os.listdir('songs/')
for familia in familias:
    #print(f'Procesando familia: {familia}')
    
    generos_path = f'songs/{familia}/'
    generos = os.listdir(generos_path)
    for genero in generos:
        #print(f'\tProcesando género: {genero}')
        
        especies_path = f'{generos_path}{genero}/'
        especies = os.listdir(especies_path)
        for especie in especies:
            #print(f'\t\tProcesando especie: {especie}')
            
            name_comun_path = f'{especies_path}{especie}/'
            name_comuns = os.listdir(name_comun_path)
            for name_comun in name_comuns:
                ruta_base = f'{name_comun_path}{name_comun}'
                #print(f'\t\t\tRuta base: {ruta_base}')
                
                nombre_archivo = f"./data/{familia}_{genero}_{especie}.csv"
                if not os.path.exists(nombre_archivo):
                    print(f'\t\t\tRuta base: {ruta_base}')
                    process_features(
                    f"{ruta_base}/",
                    "./data/"
                    f"{familia}_{genero}_{especie}"
                    )
                else:
                    pass
                    #print(f'El archivo {nombre_archivo} ya existe, saltando procesamiento.')

In [5]:
# process_features(
#     "songs/Alaudidae/Eremophila/Eremophila alpestris/HornedLark/",
#     "./data/"
#     "ElegantWoodcreeper"
# )

In [6]:
ruta_features = 'data/'
archivos_csv = os.listdir(ruta_features)
dfs = []
for archivo_csv in archivos_csv:
    # Extraer familia, género y especie del nombre del archivo
    partes_nombre = archivo_csv.split('_')
    familia = partes_nombre[0]
    genero = partes_nombre[1]
    especie = '_'.join(partes_nombre[2:]).replace('.csv', '')  # Asume que el nombre de la especie puede tener guiones bajos

    df = pd.read_csv(os.path.join(ruta_features, archivo_csv))
    # Agregar las columnas con la información extraída
    df['Familia'] = familia
    df['Genero'] = genero
    df['Especie'] = especie

    dfs.append(df)

df_final = pd.concat(dfs, ignore_index=True)
df_final.to_csv('data_total/species_features.csv', index=False)

In [22]:
import polars as pl

In [69]:
%time
# carga un archivo csv usando polars, visualiza todas las columnas
df = pl.read_csv('data_total/species_features.csv', has_header=True)
df.select(pl.col("*")).head()

CPU times: total: 0 ns
Wall time: 0 ns

shape: (5, 466)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ track_ind ┆ chroma_ce ┆ chroma_ce ┆ chroma_ce ┆ … ┆ zcr_std_0 ┆ Familia   ┆ Genero    ┆ Especie  │
│ ex        ┆ ns_kurtos ┆ ns_kurtos ┆ ns_kurtos ┆   ┆ 1         ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ is_01     ┆ is_02     ┆ is_03     ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆           ┆           ┆          │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1201      ┆ -1.231321 ┆ 1.176471  ┆ -0.934772 ┆ … ┆ 0.048615  ┆ Alaudidae ┆ Eremophil ┆ Eremophi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆ la alpes │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tris     │
│ 11505     ┆ -0.323925 ┆ 0.169799  ┆ 0.076766  ┆ … ┆ 0.028874  ┆ Alaudidae ┆ Eremophil ┆ Eremophi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆ la alpes │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tris     │
│ 11506     ┆ -0.504844 ┆ -0.152353 ┆ -0.37398  ┆ … ┆ 0.048212  ┆ Alaudidae ┆ Eremophil ┆ Eremophi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆ la alpes │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tris     │
│ 12122     ┆ 5.584173  ┆ 0.995712  ┆ 0.854311  ┆ … ┆ 0.057857  ┆ Alaudidae ┆ Eremophil ┆ Eremophi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆ la alpes │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tris     │
│ 14877     ┆ 0.784319  ┆ 0.570632  ┆ 0.716539  ┆ … ┆ 0.070321  ┆ Alaudidae ┆ Eremophil ┆ Eremophi │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ a         ┆ la alpes │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tris     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [70]:
tiranni = [
    'Philepittidae', 'Eurylaimidae', 'Calyptomenidae', 'Sapayoidae', 'Pittidae',
    'Pipridae', 'Cotingidae', 'Tityridae', 'Tyrannidae', 'Melanopareiidae', 'Conopophagidae', 
    'Thamnophilidae', 'Grallariidae', 'Rhinocryptidae', 'Formicariidae', 'Furnariidae',
]

passeri = [ 
        'Menuridae', 'Atrichornithidae', 'Climacteridae', 'Maluridae', 'Meliphagidae', 'Pardalotidae',
        'Petroicidae', 'Orthonychidae', 'Pomatostomidae', 'Cinclosomatidae', 'Neosittidae',
        'Pachycephalidae', 'Dicruridae', 'Oriolidae', 'Artamidae', 'Paradisaeidae', 'Corvidae', 
        'Cyanocorax', 'Corcoracidae', 'Irenidae', 'Laniidae', 'Vireonidae', 'Ptilonorhynchidae', 
        'Turnagridae', 'Callaeidae', 'Alaudidae', 'Chloropseidae', 'Aegithinidae', 'Picathartidae',
        'Bombycillidae', 'Ptilogonatidae', 'Cinclidae', 'Motacillidae', 'Prunellidae', 'Melanocharitidae',
        'Paramythiidae', 'Passeridae', 'Estrildidae', 'Ploceidae', 'Parulidae', 'Thraupidae', 
        'Peucedramidae', 'Fringillidae', 'Cardinalidae', 'Drepanididae', 'Emberizidae', 'Nectariniidae',
        'Dicaeidae', 'Mimidae', 'Sittidae', 'Certhiidae', 'Troglodytidae', 'Polioptilidae', 'Paridae',
        'Aegithalidae', 'Hirundinidae', 'Regulidae', 'Pycnonotidae', 'Sylviidae', 'Acrocephalidae', 
        'Locustellidae', 'Cettiidae', 'Phylloscopidae', 'Cisticolidae', 'Hypocoliidae', 'Zosteropidae',
        'Paradoxornithidae', 'Timaliidae', 'Leiothrichidae', 'Muscicapidae', 'Turdidae', 'Sturnidae',
        'Icteridae'
]

In [71]:
# def suborder(row):
#     if row['Familia'] in tiranni:
#         return 'Tyranni'
#     elif row['Familia'] in passeri:
#         return 'Passeri'
#     else:
#         return 'No definido'

In [73]:
# Aplica la lógica usando expresiones de polars
df = df.with_columns(
    pl.when(pl.col('Familia').is_in(tiranni)).then(pl.lit('Tyranni'))
    .otherwise(
        pl.when(pl.col('Familia').is_in(passeri)).then(pl.lit('Passeri'))
        .otherwise(pl.lit(None))
    ).alias('Suborder')
)

In [74]:
df.select(pl.col("*")).head()

shape: (5, 467)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ track_ind ┆ chroma_ce ┆ chroma_ce ┆ chroma_ce ┆ … ┆ Familia   ┆ Genero    ┆ Especie   ┆ Suborder │
│ ex        ┆ ns_kurtos ┆ ns_kurtos ┆ ns_kurtos ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ is_01     ┆ is_02     ┆ is_03     ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1201      ┆ -1.231321 ┆ 1.176471  ┆ -0.934772 ┆ … ┆ Alaudidae ┆ Eremophil ┆ Eremophil ┆ Passeri  │
│           ┆           ┆           ┆           ┆   ┆           ┆ a         ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alpestris ┆          │
│ 11505     ┆ -0.323925 ┆ 0.169799  ┆ 0.076766  ┆ … ┆ Alaudidae ┆ Eremophil ┆ Eremophil ┆ Passeri  │
│           ┆           ┆           ┆           ┆   ┆           ┆ a         ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alpestris ┆          │
│ 11506     ┆ -0.504844 ┆ -0.152353 ┆ -0.37398  ┆ … ┆ Alaudidae ┆ Eremophil ┆ Eremophil ┆ Passeri  │
│           ┆           ┆           ┆           ┆   ┆           ┆ a         ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alpestris ┆          │
│ 12122     ┆ 5.584173  ┆ 0.995712  ┆ 0.854311  ┆ … ┆ Alaudidae ┆ Eremophil ┆ Eremophil ┆ Passeri  │
│           ┆           ┆           ┆           ┆   ┆           ┆ a         ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alpestris ┆          │
│ 14877     ┆ 0.784319  ┆ 0.570632  ┆ 0.716539  ┆ … ┆ Alaudidae ┆ Eremophil ┆ Eremophil ┆ Passeri  │
│           ┆           ┆           ┆           ┆   ┆           ┆ a         ┆ a         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alpestris ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [75]:
# Contar el número de registros por suborder
df.group_by('Suborder').agg([
    pl.col('Suborder').count().alias('count')
])

shape: (3, 2)
┌──────────┬───────┐
│ Suborder ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ Tyranni  ┆ 52231 │
│ null     ┆ 0     │
│ Passeri  ┆ 39049 │
└──────────┴───────┘

In [77]:
df.write_csv('data_total/species_features.csv')