# Notes

In [1]:
import sys
import os
import pandas as pd
import numpy as np
from scipy import stats

import librosa
import librosa.display

from data_engineering import process_features

In [2]:
# Obtener la ruta del directorio raíz
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))

In [ ]:
familias = sorted([f for f in os.listdir('/Users/camcortes/Documents/birds-sounds/songs/') if os.path.isdir(os.path.join('/Users/camcortes/Documents/birds-sounds/songs/', f))])
for familia in familias:
    generos_path = f'/Users/camcortes/Documents/birds-sounds/songs/{familia}/'
    generos = sorted([g for g in os.listdir(generos_path) if os.path.isdir(os.path.join(generos_path, g)) and not g.startswith('.')])
    for genero in generos:
        especies_path = f'{generos_path}{genero}/'
        especies = sorted([e for e in os.listdir(especies_path) if os.path.isdir(os.path.join(especies_path, e)) and not e.startswith('.')])
        for especie in especies:
            name_comun_path = f'{especies_path}{especie}/'
            name_comuns = sorted([n for n in os.listdir(name_comun_path) if os.path.isdir(os.path.join(name_comun_path, n)) and not n.startswith('.')])
            for name_comun in name_comuns:
                ruta_base = f'{name_comun_path}{name_comun}'
                
                nombre_archivo = f"./Users/camcortes/Documents/birds-sounds/data/{familia}_{genero}_{especie}.csv"
                if not os.path.exists(nombre_archivo):
                    print(f'\t\t\tRuta base: {ruta_base}')
                    try:
                        process_features(
                            f"{ruta_base}/",
                            f"./Users/camcortes/Documents/birds-sounds/data/"
                            f"{familia}_{genero}_{especie}"
                        )
                    except Exception as e:
                        print(f'Error procesando {ruta_base}: {e}')

In [5]:
# process_features(
#     "songs/Alaudidae/Eremophila/Eremophila alpestris/HornedLark/",
#     "./data/"
#     "ElegantWoodcreeper"
# )

In [3]:
ruta_features = '/Users/camcortes/Documents/birds-sounds/data/'
archivos_csv = os.listdir(ruta_features)
dfs = []
for archivo_csv in archivos_csv:
    # Extraer familia, género y especie del nombre del archivo
    partes_nombre = archivo_csv.split('_')
    familia = partes_nombre[0]
    genero = partes_nombre[1]
    especie = '_'.join(partes_nombre[2:]).replace('.csv', '')  # Asume que el nombre de la especie puede tener guiones bajos

    df = pd.read_csv(os.path.join(ruta_features, archivo_csv))
    # Agregar las columnas con la información extraída
    df['Familia'] = familia
    df['Genero'] = genero
    df['Especie'] = especie

    dfs.append(df)

df_final = pd.concat(dfs, ignore_index=True)
df_final.to_csv('/Users/camcortes/Documents/birds-sounds/notebooks/data/species_features.csv', index=False)

In [4]:
import polars as pl

In [5]:
%time
# carga un archivo csv usando polars, visualiza todas las columnas
df = pl.read_csv('/Users/camcortes/Documents/birds-sounds/notebooks/data/species_features.csv', has_header=True)
df.select(pl.col("*")).head()

CPU times: user 1e+03 ns, sys: 1 µs, total: 2 µs
Wall time: 5.96 µs

shape: (5, 466)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ track_inde ┆ chroma_cen ┆ chroma_ce ┆ chroma_ce ┆ … ┆ zcr_std_0 ┆ Familia   ┆ Genero ┆ Especie   │
│ x          ┆ s_kurtosis ┆ ns_kurtos ┆ ns_kurtos ┆   ┆ 1         ┆ ---       ┆ ---    ┆ ---       │
│ ---        ┆ _01        ┆ is_02     ┆ is_03     ┆   ┆ ---       ┆ str       ┆ str    ┆ str       │
│ i64        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ f64       ┆           ┆        ┆           │
│            ┆ f64        ┆ f64       ┆ f64       ┆   ┆           ┆           ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 5041       ┆ -0.73778   ┆ -0.272301 ┆ -0.154337 ┆ … ┆ 0.040446  ┆ Thamnophi ┆ Pithys ┆ Pithys    │
│            ┆            ┆           ┆           ┆   ┆           ┆ lidae     ┆        ┆ albifrons │
│ 9228       ┆ 0.323404   ┆ -0.70049  ┆ -0.095855 ┆ … ┆ 0.032243  ┆ Thamnophi ┆ Pithys ┆ Pithys    │
│            ┆            ┆           ┆           ┆   ┆           ┆ lidae     ┆        ┆ albifrons │
│ 17242      ┆ -0.465705  ┆ 0.369771  ┆ -0.484454 ┆ … ┆ 0.018813  ┆ Thamnophi ┆ Pithys ┆ Pithys    │
│            ┆            ┆           ┆           ┆   ┆           ┆ lidae     ┆        ┆ albifrons │
│ 28104      ┆ 0.098275   ┆ 1.052437  ┆ -0.524402 ┆ … ┆ 0.055425  ┆ Thamnophi ┆ Pithys ┆ Pithys    │
│            ┆            ┆           ┆           ┆   ┆           ┆ lidae     ┆        ┆ albifrons │
│ 34382      ┆ 0.285729   ┆ 0.213107  ┆ -0.80529  ┆ … ┆ 0.017153  ┆ Thamnophi ┆ Pithys ┆ Pithys    │
│            ┆            ┆           ┆           ┆   ┆           ┆ lidae     ┆        ┆ albifrons │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [6]:
tiranni = [
    'Philepittidae', 'Eurylaimidae', 'Calyptomenidae', 'Sapayoidae', 'Pittidae',
    'Pipridae', 'Cotingidae', 'Tityridae', 'Tyrannidae', 'Melanopareiidae', 'Conopophagidae', 
    'Thamnophilidae', 'Grallariidae', 'Rhinocryptidae', 'Formicariidae', 'Furnariidae'
]

passeri = [ 
        'Menuridae', 'Atrichornithidae', 'Climacteridae', 'Maluridae', 'Meliphagidae', 'Pardalotidae',
        'Petroicidae', 'Orthonychidae', 'Pomatostomidae', 'Cinclosomatidae', 'Neosittidae',
        'Pachycephalidae', 'Dicruridae', 'Oriolidae', 'Artamidae', 'Paradisaeidae', 'Corvidae', 
        'Cyanocorax', 'Corcoracidae', 'Irenidae', 'Laniidae', 'Vireonidae', 'Ptilonorhynchidae', 
        'Turnagridae', 'Callaeidae', 'Alaudidae', 'Chloropseidae', 'Aegithinidae', 'Picathartidae',
        'Bombycillidae', 'Ptilogonatidae', 'Cinclidae', 'Motacillidae', 'Prunellidae', 'Melanocharitidae',
        'Paramythiidae', 'Passeridae', 'Estrildidae', 'Ploceidae', 'Parulidae', 'Thraupidae', 
        'Peucedramidae', 'Fringillidae', 'Cardinalidae', 'Drepanididae', 'Emberizidae', 'Nectariniidae',
        'Dicaeidae', 'Mimidae', 'Sittidae', 'Certhiidae', 'Troglodytidae', 'Polioptilidae', 'Paridae',
        'Aegithalidae', 'Hirundinidae', 'Regulidae', 'Pycnonotidae', 'Sylviidae', 'Acrocephalidae', 
        'Locustellidae', 'Cettiidae', 'Phylloscopidae', 'Cisticolidae', 'Hypocoliidae', 'Zosteropidae',
        'Paradoxornithidae', 'Timaliidae', 'Leiothrichidae', 'Muscicapidae', 'Turdidae', 'Sturnidae',
        'Icteridae'
]

In [71]:
# def suborder(row):
#     if row['Familia'] in tiranni:
#         return 'Tyranni'
#     elif row['Familia'] in passeri:
#         return 'Passeri'
#     else:
#         return 'No definido'

In [7]:
# Aplica la lógica usando expresiones de polars
df = df.with_columns(
    pl.when(pl.col('Familia').is_in(tiranni)).then(pl.lit('Tyranni'))
    .otherwise(
        pl.when(pl.col('Familia').is_in(passeri)).then(pl.lit('Passeri'))
        .otherwise(pl.lit(None))
    ).alias('Suborder')
)

In [8]:
df.select(pl.col("*")).head()

shape: (5, 467)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬────────┬───────────┬──────────┐
│ track_inde ┆ chroma_cen ┆ chroma_cen ┆ chroma_ce ┆ … ┆ Familia   ┆ Genero ┆ Especie   ┆ Suborder │
│ x          ┆ s_kurtosis ┆ s_kurtosis ┆ ns_kurtos ┆   ┆ ---       ┆ ---    ┆ ---       ┆ ---      │
│ ---        ┆ _01        ┆ _02        ┆ is_03     ┆   ┆ str       ┆ str    ┆ str       ┆ str      │
│ i64        ┆ ---        ┆ ---        ┆ ---       ┆   ┆           ┆        ┆           ┆          │
│            ┆ f64        ┆ f64        ┆ f64       ┆   ┆           ┆        ┆           ┆          │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪════════╪═══════════╪══════════╡
│ 5041       ┆ -0.73778   ┆ -0.272301  ┆ -0.154337 ┆ … ┆ Thamnophi ┆ Pithys ┆ Pithys    ┆ Tyranni  │
│            ┆            ┆            ┆           ┆   ┆ lidae     ┆        ┆ albifrons ┆          │
│ 9228       ┆ 0.323404   ┆ -0.70049   ┆ -0.095855 ┆ … ┆ Thamnophi ┆ Pithys ┆ Pithys    ┆ Tyranni  │
│            ┆            ┆            ┆           ┆   ┆ lidae     ┆        ┆ albifrons ┆          │
│ 17242      ┆ -0.465705  ┆ 0.369771   ┆ -0.484454 ┆ … ┆ Thamnophi ┆ Pithys ┆ Pithys    ┆ Tyranni  │
│            ┆            ┆            ┆           ┆   ┆ lidae     ┆        ┆ albifrons ┆          │
│ 28104      ┆ 0.098275   ┆ 1.052437   ┆ -0.524402 ┆ … ┆ Thamnophi ┆ Pithys ┆ Pithys    ┆ Tyranni  │
│            ┆            ┆            ┆           ┆   ┆ lidae     ┆        ┆ albifrons ┆          │
│ 34382      ┆ 0.285729   ┆ 0.213107   ┆ -0.80529  ┆ … ┆ Thamnophi ┆ Pithys ┆ Pithys    ┆ Tyranni  │
│            ┆            ┆            ┆           ┆   ┆ lidae     ┆        ┆ albifrons ┆          │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴────────┴───────────┴──────────┘

In [9]:
# Contar el número de registros por suborder
df.group_by('Suborder').agg([
    pl.col('Suborder').count().alias('count')
])

shape: (3, 2)
┌──────────┬───────┐
│ Suborder ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ null     ┆ 0     │
│ Passeri  ┆ 39049 │
│ Tyranni  ┆ 52231 │
└──────────┴───────┘

In [10]:
df.write_csv('data/species_features.csv')