In [1]:
#!pip install keras_cv tensorflow_io

In [2]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import Model
import os
import numpy as np
import pandas as pd
from typing import Dict, Any, Optional, Union, Tuple, List, Callable

# from google.colab import drive, files
# drive.mount('/content/drive')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.max_colwidth', None)

In [3]:
# !cp -r "/content/drive/MyDrive/model" /content/
# !cp -r "/content/drive/MyDrive/Test" /content/
# !cp -r "/content/drive/MyDrive/images_test/images_spectograms" /content/

In [4]:
from src.model_trainer import ModelTrainer

model_name = "ResNet152V2" #"MobileNetV3Large" #"EfficientNetV2L" #"ResNet152V2" #"EfficientNetB7"

model_trainer = ModelTrainer(
    model_name=model_name,
    img_shape=(128, 256, 1),
    n_classes=667,
    dropout_rate=0.01,
    label_smoothing=0.3,
    fine_tune_layers=0
)

model = model_trainer.create_model()
model.summary()
model.load_weights(f"./models/weights_{model_name}.weights.h5")
tf.keras.backend.clear_session()

Model: "ResNet152V2_classifier"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 128, 256, 1)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 128, 256, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ preprocess_input (Lambda)       │ (None, 128, 256, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ resnet152v2 (Functional)        │ (None, 2048)           │    58,331,648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ top_dropout (Dropout)           │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ logits (Dense)                  │ (None, 667)            │     1,366,683 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 59,698,331 (227.73 MB)

 Trainable params: 59,554,587 (227.18 MB)

 Non-trainable params: 143,744 (561.50 KB)

/Users/camcortes/Documents/birds-sounds/.venv-birds-song/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 368 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [5]:
# cargar el label encoder del pickle
import pickle

with open(f'./models/label_encoder_{model_name}.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

In [6]:
from src.image_preprocessor import ImagePreprocessor

preprocessor = ImagePreprocessor(label_encoder=label_encoder)
data = preprocessor.load_data_from_directory("src/data/images_test/images_spectograms")
data.head()

/Users/camcortes/Documents/birds-sounds/.venv-birds-song/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,label,image_path
0,Acropternis orthonyx,src/data/images_test/images_spectograms/Acropternis orthonyx/121142_13.jpeg
1,Acropternis orthonyx,src/data/images_test/images_spectograms/Acropternis orthonyx/511703_5.jpeg
2,Acropternis orthonyx,src/data/images_test/images_spectograms/Acropternis orthonyx/461011_0.jpeg
3,Acropternis orthonyx,src/data/images_test/images_spectograms/Acropternis orthonyx/621780_9.jpeg
4,Acropternis orthonyx,src/data/images_test/images_spectograms/Acropternis orthonyx/428484_0.jpeg

In [7]:
import random
from tqdm import tqdm

def especie_batch(data):
    species = list(set(data["label"]))
    num_species = len(species)
    for i, specie in enumerate(tqdm(species, desc=f"Especies procesadas")):
        print(f"\nEspecie {i+1} de {(num_species)}, ({specie})")
        yield specie

def specie_ds(data, gen):
    try:
        specie = next(gen)
        df = data[data["label"] == specie]
        if df.empty:
            print(f"No more species")
            return None, None
    except StopIteration:
        return None, None
    return specie, preprocessor.create_validation_dataset(df)

In [8]:
import matplotlib.pyplot as plt
import numpy as np

def calcular_incertidumbre(dataset_espectrogramas, modelo):
    predicciones_mc = []
    confianzas_mc = []

    etiqueta_real_lista =[]
    etiqueta_inferencia_lista = []

    if dataset_espectrogramas:
        for imagenes_batch, etiquetas_batch in dataset_espectrogramas.take(1):
            num_imagenes = len(imagenes_batch)

            # MONTE CARLO DROPOUT: Múltiples pasadas con training=True
            for idx in range(num_imagenes):
                imagen = imagenes_batch[idx]
                # Añadir una dimensión de batch (necesario para la inferencia)
                imagen_batch = tf.expand_dims(imagen, axis=0)
                etiqueta_real = tf.argmax(etiquetas_batch[idx])

                etiqueta_real_lista.append(etiqueta_real.numpy())

                #for iteracion in range(5):
                logits = modelo(imagen_batch, training=True)
                probabilidades = tf.nn.softmax(logits, axis=-1).numpy()
                clase_predicha = np.argmax(probabilidades, axis=-1)[0]
                confianza = probabilidades[0, clase_predicha]

                predicciones_mc.append(clase_predicha)
                confianzas_mc.append(confianza)

                # Predicción convencional (sin dropout activo)
                logits_inferencia = modelo(imagen_batch, training=False)
                #logits_inferencia = modelo.predict(imagen_batch)
                probabilidades_inferencia = tf.nn.softmax(logits_inferencia, axis=-1).numpy()
                clase_predicha_inferencia = np.argmax(probabilidades_inferencia, axis=-1)[0]
                confianza_inferencia = probabilidades_inferencia[0, clase_predicha_inferencia]

                etiqueta_inferencia_lista.append(clase_predicha_inferencia)

                #print(f"\nClase real: {etiqueta_real}")
                #print(f"Clase predicha (modo inferencia): {clase_predicha_inferencia}")
                #print(f"Confianza (modo inferencia): {confianza_inferencia:.4f} ({confianza_inferencia*100:.2f}%)")

            # Imagen
            # plt.imshow(imagen.numpy().squeeze(), cmap='inferno')
            # plt.title(f"Predicha: {clase_predicha_inferencia} (Inferencia)")
            # plt.axis('off')
            # plt.show()

    return predicciones_mc, confianzas_mc, etiqueta_inferencia_lista, etiqueta_real_lista

In [9]:
dataset_generado = especie_batch(data)

resultados = {}
for i in range(data["label"].nunique()):
    especie, dataset_especie = specie_ds(data, dataset_generado)
    predicciones_mc, confianzas_mc, clase_predicha_inferencia, etiqueta_real = calcular_incertidumbre(dataset_especie, model)
    resultados[especie] = {
        "clase_real": etiqueta_real,
        "clase_predicha_inferencia": clase_predicha_inferencia,
        "predicciones_mc": predicciones_mc,
        "confianzas_mc": confianzas_mc,
    }

Especies procesadas:  87%|████████▋ | 583/667 [7:20:19<1:17:34, 55.41s/it]

Especie 584 de 667, (Ammodramus savannarum)

Especies procesadas:  88%|████████▊ | 584/667 [7:21:43<1:28:27, 63.95s/it]

Especie 585 de 667, (Myiarchus tuberculifer)

Especies procesadas:  88%|████████▊ | 585/667 [7:23:08<1:36:01, 70.26s/it]

Especie 586 de 667, (Scytalopus chocoensis)

Especies procesadas:  88%|████████▊ | 586/667 [7:23:46<1:21:52, 60.65s/it]

Especie 587 de 667, (Attila spadiceus)

Especies procesadas:  88%|████████▊ | 587/667 [7:25:06<1:28:18, 66.23s/it]

Especie 588 de 667, (Euphonia mesochrysa)

Especies procesadas:  88%|████████▊ | 588/667 [7:25:40<1:14:47, 56.81s/it]

Especie 589 de 667, (Henicorhina negreti)

Especies procesadas:  88%|████████▊ | 589/667 [7:26:00<59:08, 45.50s/it]

Especie 590 de 667, (Molothrus bonariensis)

Especies procesadas:  88%|████████▊ | 590/667 [7:27:02<1:04:50, 50.53s/it]

Especie 591 de 667, (Anabacerthia variegaticeps)

Especies procesadas:  89%|████████▊ | 591/667 [7:27:38<58:25, 46.13s/it]

Especie 592 de 667, (Cantorchilus leucotis)

Especies procesadas:  89%|████████▉ | 592/667 [7:28:39<1:03:28, 50.78s/it]

Especie 593 de 667, (Thamnophilus aethiops)

Especies procesadas:  89%|████████▉ | 593/667 [7:29:30<1:02:39, 50.81s/it]

Especie 594 de 667, (Scytalopus stilesi)

Especies procesadas:  89%|████████▉ | 594/667 [7:29:48<49:46, 40.91s/it]

Especie 595 de 667, (Capsiempis flaveola)

Especies procesadas:  89%|████████▉ | 595/667 [7:30:50<56:37, 47.19s/it]

Especie 596 de 667, (Vireolanius leucotis)

Especies procesadas:  89%|████████▉ | 596/667 [7:31:36<55:27, 46.86s/it]

Especie 597 de 667, (Myrmelastes schistaceus)

Especies procesadas:  90%|████████▉ | 597/667 [7:31:53<44:13, 37.91s/it]

Especie 598 de 667, (Mionectes striaticollis)

Especies procesadas:  90%|████████▉ | 598/667 [7:32:15<38:11, 33.21s/it]

Especie 599 de 667, (Nephelomyias pulcher)

Especies procesadas:  90%|████████▉ | 599/667 [7:32:27<30:12, 26.65s/it]

Especie 600 de 667, (Microbates collaris)

Especies procesadas:  90%|████████▉ | 600/667 [7:32:51<29:01, 25.99s/it]

Especie 601 de 667, (Dendrexetastes rufigula)

Especies procesadas:  90%|█████████ | 601/667 [7:33:32<33:24, 30.37s/it]

Especie 602 de 667, (Scytalopus atratus)

Especies procesadas:  90%|█████████ | 602/667 [7:34:33<42:52, 39.58s/it]

Especie 603 de 667, (Selenidera reinwardtii)

Especies procesadas:  90%|█████████ | 603/667 [7:34:52<35:50, 33.60s/it]

Especie 604 de 667, (Dubusia taeniata)

Especies procesadas:  91%|█████████ | 604/667 [7:35:51<43:09, 41.10s/it]

Especie 605 de 667, (Tangara labradorides)

Especies procesadas:  91%|█████████ | 605/667 [7:36:06<34:28, 33.37s/it]

Especie 606 de 667, (Vireo altiloquus)

Especies procesadas:  91%|█████████ | 606/667 [7:36:52<37:41, 37.08s/it]

Especie 607 de 667, (Pheugopedius sclateri)

Especies procesadas:  91%|█████████ | 607/667 [7:37:54<44:26, 44.44s/it]

Especie 608 de 667, (Grallaria dignissima)

Especies procesadas:  91%|█████████ | 608/667 [7:38:18<37:43, 38.37s/it]

Especie 609 de 667, (Terenotriccus erythrurus)

Especies procesadas:  91%|█████████▏| 609/667 [7:38:29<29:19, 30.33s/it]

Especie 610 de 667, (Spinus magellanicus)

Especies procesadas:  91%|█████████▏| 610/667 [7:39:10<31:38, 33.31s/it]

Especie 611 de 667, (Platyrinchus mystaceus)

Especies procesadas:  92%|█████████▏| 611/667 [7:39:55<34:26, 36.90s/it]

Especie 612 de 667, (Aulacorhynchus albivitta)

Especies procesadas:  92%|█████████▏| 612/667 [7:40:56<40:28, 44.16s/it]

Especie 613 de 667, (Vireo flavoviridis)

Especies procesadas:  92%|█████████▏| 613/667 [7:41:58<44:29, 49.43s/it]

Especie 614 de 667, (Inezia subflava)

Especies procesadas:  92%|█████████▏| 614/667 [7:42:05<32:31, 36.81s/it]

Especie 615 de 667, (Arremon castaneiceps)

Especies procesadas:  92%|█████████▏| 615/667 [7:42:27<27:57, 32.26s/it]

Especie 616 de 667, (Sipia palliata)

Especies procesadas:  92%|█████████▏| 616/667 [7:43:00<27:45, 32.65s/it]

Especie 617 de 667, (Anabacerthia striaticollis)

Especies procesadas:  93%|█████████▎| 617/667 [7:43:24<24:59, 29.99s/it]

Especie 618 de 667, (Empidonax traillii)

Especies procesadas:  93%|█████████▎| 618/667 [7:44:28<32:48, 40.18s/it]

Especie 619 de 667, (Troglodytes solstitialis)

Especies procesadas:  93%|█████████▎| 619/667 [7:45:20<35:03, 43.81s/it]

Especie 620 de 667, (Myrmophylax atrothorax)

Especies procesadas:  93%|█████████▎| 620/667 [7:46:24<39:04, 49.87s/it]

Especie 621 de 667, (Thripadectes holostictus)

Especies procesadas:  93%|█████████▎| 621/667 [7:47:29<41:32, 54.18s/it]

Especie 622 de 667, (Sipia laemosticta)

Especies procesadas:  93%|█████████▎| 622/667 [7:48:15<38:50, 51.78s/it]

Especie 623 de 667, (Sclerurus albigularis)

Especies procesadas:  93%|█████████▎| 623/667 [7:49:15<39:55, 54.45s/it]

Especie 624 de 667, (Manacus manacus)

Especies procesadas:  94%|█████████▎| 624/667 [7:50:06<38:08, 53.23s/it]

Especie 625 de 667, (Dysithamnus mentalis)

Especies procesadas:  94%|█████████▎| 625/667 [7:51:09<39:16, 56.10s/it]

Especie 626 de 667, (Myrmotherula ignota)

Especies procesadas:  94%|█████████▍| 626/667 [7:51:37<32:37, 47.74s/it]

Especie 627 de 667, (Rhynchocyclus olivaceus)

Especies procesadas:  94%|█████████▍| 627/667 [7:52:04<27:43, 41.58s/it]

Especie 628 de 667, (Stilpnia cyanicollis)

Especies procesadas:  94%|█████████▍| 628/667 [7:52:21<22:15, 34.24s/it]

Especie 629 de 667, (Machetornis rixosa)

Especies procesadas:  94%|█████████▍| 629/667 [7:53:17<25:42, 40.59s/it]

Especie 630 de 667, (Microrhopias quixensis)

Especies procesadas:  94%|█████████▍| 630/667 [7:54:18<28:48, 46.71s/it]

Especie 631 de 667, (Anisognathus lacrymosus)

Especies procesadas:  95%|█████████▍| 631/667 [7:54:39<23:31, 39.20s/it]

Especie 632 de 667, (Myrmornis torquata)

Especies procesadas:  95%|█████████▍| 632/667 [7:55:03<20:10, 34.59s/it]

Especie 633 de 667, (Rhegmatorhina melanosticta)

Especies procesadas:  95%|█████████▍| 633/667 [7:55:24<17:18, 30.54s/it]

Especie 634 de 667, (Thamnophilus multistriatus)

Especies procesadas:  95%|█████████▌| 634/667 [7:56:05<18:29, 33.63s/it]

Especie 635 de 667, (Contopus fumigatus)

Especies procesadas:  95%|█████████▌| 635/667 [7:56:43<18:41, 35.05s/it]

Especie 636 de 667, (Cercomacroides nigrescens)

Especies procesadas:  95%|█████████▌| 636/667 [7:57:45<22:11, 42.94s/it]

Especie 637 de 667, (Herpsilochmus rufimarginatus)

Especies procesadas:  96%|█████████▌| 637/667 [7:58:25<21:00, 42.03s/it]

Especie 638 de 667, (Formicivora grisea)

Especies procesadas:  96%|█████████▌| 638/667 [7:59:05<20:05, 41.56s/it]

Especie 639 de 667, (Sipia berlepschi)

Especies procesadas:  96%|█████████▌| 639/667 [7:59:40<18:29, 39.62s/it]

Especie 640 de 667, (Thamnophilus murinus)

Especies procesadas:  96%|█████████▌| 640/667 [8:00:18<17:37, 39.15s/it]

Especie 641 de 667, (Xiphorhynchus elegans)

Especies procesadas:  96%|█████████▌| 641/667 [8:00:36<14:09, 32.67s/it]

Especie 642 de 667, (Dumetella carolinensis)

Especies procesadas:  96%|█████████▋| 642/667 [8:01:39<17:22, 41.70s/it]

Especie 643 de 667, (Phaeomyias murina)

Especies procesadas:  96%|█████████▋| 643/667 [8:02:39<18:56, 47.35s/it]

Especie 644 de 667, (Cyphorhinus arada)

Especies procesadas:  97%|█████████▋| 644/667 [8:03:39<19:38, 51.23s/it]

Especie 645 de 667, (Thripophaga fusciceps)

Especies procesadas:  97%|█████████▋| 645/667 [8:04:03<15:42, 42.85s/it]

Especie 646 de 667, (Anisognathus igniventris)

Especies procesadas:  97%|█████████▋| 646/667 [8:04:30<13:20, 38.11s/it]

Especie 647 de 667, (Scytalopus spillmanni)

Especies procesadas:  97%|█████████▋| 647/667 [8:05:30<14:54, 44.72s/it]

Especie 648 de 667, (Asthenes flammulata)

Especies procesadas:  97%|█████████▋| 648/667 [8:05:52<11:59, 37.86s/it]

Especie 649 de 667, (Hylophilus flavipes)

Especies procesadas:  97%|█████████▋| 649/667 [8:06:52<13:24, 44.69s/it]

Especie 650 de 667, (Xenops minutus)

Especies procesadas:  97%|█████████▋| 650/667 [8:07:54<14:03, 49.63s/it]

Especie 651 de 667, (Cinnycerthia olivascens)

Especies procesadas:  98%|█████████▊| 651/667 [8:08:55<14:11, 53.20s/it]

Especie 652 de 667, (Buthraupis montana)

Especies procesadas:  98%|█████████▊| 652/667 [8:09:25<11:33, 46.25s/it]

Especie 653 de 667, (Emberizoides herbicola)

Especies procesadas:  98%|█████████▊| 653/667 [8:10:25<11:45, 50.41s/it]

Especie 654 de 667, (Ixothraupis rufigula)

Especies procesadas:  98%|█████████▊| 654/667 [8:10:39<08:32, 39.44s/it]

Especie 655 de 667, (Myrmotherula multostriata)

Especies procesadas:  98%|█████████▊| 655/667 [8:11:24<08:13, 41.16s/it]

Especie 656 de 667, (Molothrus oryzivorus)

Especies procesadas:  98%|█████████▊| 656/667 [8:11:40<06:10, 33.68s/it]

Especie 657 de 667, (Anthus rubescens)

Especies procesadas:  99%|█████████▊| 657/667 [8:12:03<05:03, 30.33s/it]

Especie 658 de 667, (Chlorophonia pyrrhophrys)

Especies procesadas:  99%|█████████▊| 658/667 [8:12:21<03:59, 26.58s/it]

Especie 659 de 667, (Sclateria naevia)

Especies procesadas:  99%|█████████▉| 659/667 [8:13:21<04:53, 36.75s/it]

Especie 660 de 667, (Spinus olivaceus)

Especies procesadas:  99%|█████████▉| 660/667 [8:13:35<03:29, 29.86s/it]

Especie 661 de 667, (Sclerurus rufigularis)

Especies procesadas:  99%|█████████▉| 661/667 [8:14:06<03:01, 30.21s/it]

Especie 662 de 667, (Inezia caudata)

Especies procesadas:  99%|█████████▉| 662/667 [8:14:17<02:02, 24.43s/it]

Especie 663 de 667, (Procnias averano)

Especies procesadas:  99%|█████████▉| 663/667 [8:14:57<01:56, 29.23s/it]

Especie 664 de 667, (Thripadectes melanorhynchus)

Especies procesadas: 100%|█████████▉| 664/667 [8:15:19<01:20, 26.82s/it]

Especie 665 de 667, (Euphonia chlorotica)

Especies procesadas: 100%|█████████▉| 665/667 [8:16:17<01:12, 36.37s/it]

Especie 666 de 667, (Sphenopsis melanotis)

Especies procesadas: 100%|█████████▉| 666/667 [8:16:38<00:31, 31.58s/it]

Especie 667 de 667, (Grallaria saturata)

In [15]:
# Alternativa más detallada si las longitudes de las listas varían
filas = []
for especie, datos in resultados.items():
    clase_real = datos["clase_real"]
    clase_predicha = datos["clase_predicha_inferencia"]
    predicciones = datos["predicciones_mc"]
    confianzas = datos["confianzas_mc"]

    max_len = max(len(clase_real), len(clase_predicha), len(predicciones), len(confianzas))

    for i in range(max_len):
        filas.append({
            "especie": especie,
            'registros': 1,
            "clase_real": clase_real[i] if i < len(clase_real) else None,
            "clase_predicha": clase_predicha[i] if i < len(clase_predicha) else None,
            "prediccion_mc": predicciones[i] if i < len(predicciones) else None,
            "confianza_mc": confianzas[i] if i < len(confianzas) else None,
            'true_positive': 1 if clase_real[i] == clase_predicha[i] else 0,
            'true_positivo_mc': 1 if clase_real[i] == predicciones[i] else 0,
        })

df_final = pd.DataFrame(filas)
print(df_final.shape)
#df_final

(32279, 8)

In [16]:
df_final.to_csv("src/data/incertidumbres_ResNet152V2.csv", index=False)

In [17]:
df = pd.read_csv("src/data/incertidumbres_ResNet152V2.csv")
df.head()

,especie,registros,clase_real,clase_predicha,prediccion_mc,confianza_mc,true_positive,true_positivo_mc
0,Catharus aurantiirostris,1,71,71,641,0.00,1,0
1,Catharus aurantiirostris,1,71,604,60,0.00,0,0
2,Catharus aurantiirostris,1,71,71,266,0.01,1,0
3,Catharus aurantiirostris,1,71,71,71,0.00,1,1
4,Catharus aurantiirostris,1,71,71,71,0.01,1,1

* Calcular la moda
* Calcular la distribución

In [18]:
df = df.groupby('especie').agg(
    {
        'registros': 'sum',
        'true_positive': 'mean',
        'true_positivo_mc': 'mean',
        'confianza_mc': 'max',

    }
).reset_index()

In [ ]:
def calcular_proporcion(row):
    real = set(row['clase_real'])
    predicha = set(row['clase_prediche_inferencia'])

    # Elementos comunes entre ambas listas
    elementos_comunes = len(real.intersection(predicha))

    # Total de elementos únicos en clase_real
    total_elementos_real = len(real)

    # Calcula la proporción (evitando división por cero)
    if total_elementos_real > 0:
        return elementos_comunes / total_elementos_real
    else:
        return 0

df['proporcion_coincidencia'] = df.apply(calcular_proporcion, axis=1)
df['porcentaje_coincidencia'] = df['proporcion_coincidencia'] * 100

In [19]:
df.to_csv("/content/drive/MyDrive/Incertidumbres/incertidumbres_ResNet152V2.csv")
#guardar excel
df.to_excel("/content/drive/MyDrive/Incertidumbres/incertidumbres_ResNet152V2.xlsx")

In [ ]:
all_probs = np.concatenate(probabilities, axis=0)
mean_prob = np.mean(all_probs, axis=0)
# Entropía de la distribución promedio
predictive_entropy = -np.sum(mean_prob * np.log(mean_prob + 1e-9))
print("Entropía de predicción:", predictive_entropy)

In [ ]:
np.exp(0.00974931)