In [1]:
library(tidyverse)

Warning message:
"package 'tidyverse' was built under R version 4.4.1"
Warning message:
"package 'ggplot2' was built under R version 4.4.1"
Warning message:
"package 'tibble' was built under R version 4.2.3"
Warning message:
"package 'tidyr' was built under R version 4.2.3"
Warning message:
"package 'readr' was built under R version 4.2.3"
Warning message:
"package 'purrr' was built under R version 4.2.3"
Warning message:
"package 'dplyr' was built under R version 4.2.3"
Warning message:
"package 'stringr' was built under R version 4.4.1"
Warning message:
"package 'forcats' was built under R version 4.4.1"
Warning message:
"package 'lubridate' was built under R version 4.2.3"
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.1     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
data <- read.csv("./data_total/species_features.csv")

In [3]:
head(data)

  track_index chroma_cens_kurtosis_01 chroma_cens_kurtosis_02
1  1201       -1.2313211               1.1764712
2 11505       -0.3239248               0.1697991
3 11506       -0.5048444              -0.1523530
4 12122        5.5841732               0.9957120
5 14877        0.7843192               0.5706322
6 16969        0.2844987               0.8647149
  chroma_cens_kurtosis_03 chroma_cens_kurtosis_04 chroma_cens_kurtosis_05
1 -0.93477201              0.4249985              -1.4859222
2  0.07676578             -0.2299709              -0.5238988
3 -0.37397957             -0.1322842              -0.3294694
4  0.85431051              1.0433702               2.7777658
5  0.71653938              1.1871552               0.1227884
6 -1.12905085             -1.0708022              -0.3297772
  chroma_cens_kurtosis_06 chroma_cens_kurtosis_07 chroma_cens_kurtosis_08
1  -0.8643601              -0.5083787               0.04958701
2   0.5272238               0.8945315              -0.46702456
3  -0.4217844               0.2001784               0.36158204
4 193.9108887               1.4579825               1.97760248
5 163.7941132             176.8627777             163.28526306
6   0.5946059               0.9848001              -0.77161908
  chroma_cens_kurtosis_09 ⋯ zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01
1  -0.9532032             ⋯ 0.4526367  0.15667226  0.14453125    0.067382812
2  -0.8512831             ⋯ 0.2587891  0.03670751  0.03173828    0.007324219
3   0.0843780             ⋯ 0.2695312  0.08398181  0.07470703    0.000000000
4   1.8398285             ⋯ 0.4096680  0.31668145  0.33837891    0.118652344
5 165.7692108             ⋯ 0.4252930  0.30245362  0.30468750    0.000000000
6  -0.5191646             ⋯ 0.2548828  0.07318549  0.05322266    0.017089844
  zcr_skew_01 zcr_std_01 Familia   Genero     Especie              Suborder
1  3.3190255  0.04861468 Alaudidae Eremophila Eremophila alpestris Passeri
2  4.2743468  0.02887429 Alaudidae Eremophila Eremophila alpestris Passeri
3  0.7956747  0.04821210 Alaudidae Eremophila Eremophila alpestris Passeri
4 -0.8622858  0.05785674 Alaudidae Eremophila Eremophila alpestris Passeri
5 -0.2442116  0.07032102 Alaudidae Eremophila Eremophila alpestris Passeri
6  1.4726595  0.04490838 Alaudidae Eremophila Eremophila alpestris Passeri

In [4]:
# eliminar las columnas familia, genero y suborder
data <- data %>% 
    select(-c(Familia, Genero, Suborder, track_index))

In [5]:
head(data, 4)

  chroma_cens_kurtosis_01 chroma_cens_kurtosis_02 chroma_cens_kurtosis_03
1 -1.2313211               1.1764712              -0.93477201
2 -0.3239248               0.1697991               0.07676578
3 -0.5048444              -0.1523530              -0.37397957
4  5.5841732               0.9957120               0.85431051
  chroma_cens_kurtosis_04 chroma_cens_kurtosis_05 chroma_cens_kurtosis_06
1  0.4249985              -1.4859222               -0.8643601
2 -0.2299709              -0.5238988                0.5272238
3 -0.1322842              -0.3294694               -0.4217844
4  1.0433702               2.7777658              193.9108887
  chroma_cens_kurtosis_07 chroma_cens_kurtosis_08 chroma_cens_kurtosis_09
1 -0.5083787               0.04958701             -0.9532032
2  0.8945315              -0.46702456             -0.8512831
3  0.2001784               0.36158204              0.0843780
4  1.4579825               1.97760248              1.8398285
  chroma_cens_kurtosis_10 ⋯ tonnetz_std_05 tonnetz_std_06 zcr_kurtosis_01
1 -0.993963718            ⋯ 0.01248795     0.01669431     13.4743588
2 -0.609040260            ⋯ 0.02282363     0.02617855     20.3813515
3 -0.007186174            ⋯ 0.02282443     0.02435479      0.1822542
4  1.787970066            ⋯ 0.01589731     0.01644695     -0.3440694
  zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01  zcr_skew_01 zcr_std_01
1 0.4526367  0.15667226  0.14453125    0.067382812  3.3190255  0.04861468
2 0.2587891  0.03670751  0.03173828    0.007324219  4.2743468  0.02887429
3 0.2695312  0.08398181  0.07470703    0.000000000  0.7956747  0.04821210
4 0.4096680  0.31668145  0.33837891    0.118652344 -0.8622858  0.05785674
  Especie
1 Eremophila alpestris
2 Eremophila alpestris
3 Eremophila alpestris
4 Eremophila alpestris

In [6]:
# Agrupar por especie y calcular la media de las variables
data_summary <- data %>%
  group_by(Especie) %>%
  summarise(across(where(is.numeric), \(x) mean(x, na.rm = TRUE)))

In [7]:
missing_percentage <- sapply(data_summary, function(x) mean(is.na(x)))

columns_to_keep <- names(missing_percentage[missing_percentage <= 0.8])
data_cleaned <- data_summary[, columns_to_keep]

In [8]:
dim(data)

[1] 101200    463

In [9]:
dim(data_cleaned)
head(data_cleaned)

[1] 992 379

  Especie                  chroma_cens_kurtosis_01 chroma_cens_kurtosis_02
1 Acropternis orthonyx     1.6035175               1.9254269
2 Agriornis albicauda      0.8044930               0.1689194
3 Agriornis montanus       3.1259965               5.9364330
4 Alopochelidon fucata     0.4226607               0.3066941
5 Amblycercus holosericeus 0.2142845               0.4114130
6 Ammodramus aurifrons     2.5038159               1.8160115
  chroma_cens_kurtosis_03 chroma_cens_kurtosis_04 chroma_cens_kurtosis_05
1 2.0113514               0.9679911               1.76944194
2 0.6051555               0.1904388               1.53247590
3 5.6533131               4.0736154               3.57897102
4 0.3579240               0.9576736               0.66702319
5 0.2002995               0.1841674               0.09095704
6 0.5719813               0.8728038               0.48574777
  chroma_cens_kurtosis_06 chroma_cens_kurtosis_07 chroma_cens_kurtosis_08
1  6.0204999               1.9440984               1.4049276
2 13.8752144              13.4608701              13.5067325
3 51.8848434              65.7252112              49.8288544
4  2.5535917              14.6005357               9.8852426
5  0.2686725               0.2038994               0.1390147
6  4.1884804               6.1361146               5.2165309
  chroma_cens_kurtosis_09 ⋯ tonnetz_std_04 tonnetz_std_05 tonnetz_std_06
1  3.698810               ⋯ 0.08159752     0.03028516     0.03343773
2 11.323860               ⋯ 0.05054540     0.02022468     0.02087898
3 27.685244               ⋯ 0.06501535     0.02367763     0.02268967
4  5.031717               ⋯ 0.04889180     0.02007483     0.02148614
5  0.831263               ⋯ 0.07183474     0.03026074     0.02905769
6  4.617376               ⋯ 0.05195927     0.02112090     0.02126104
  zcr_kurtosis_01 zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01 zcr_skew_01
1  7.725479       0.3009133  0.1296930   0.1308894     0.02853644 0.8610324
2  6.001015       0.4113281  0.1702988   0.1711426     0.04782715 0.3262133
3 12.757831       0.3662598  0.1772626   0.1799683     0.04099121 0.2851319
4  4.589060       0.2967936  0.1504630   0.1504313     0.03927409 0.4392728
5  7.620865       0.3014818  0.1337720   0.1304507     0.03787895 0.8371403
6  3.920711       0.3968348  0.2177199   0.2019141     0.05942462 0.5777356
  zcr_std_01
1 0.03859638
2 0.04780803
3 0.03937832
4 0.03528906
5 0.03968411
6 0.06110676

In [10]:
data_summary[!complete.cases(data_summary),]

  Especie             chroma_cens_kurtosis_01 chroma_cens_kurtosis_02
1 Gymnoderus foetidus 0.7716391               -0.8427246
  chroma_cens_kurtosis_03 chroma_cens_kurtosis_04 chroma_cens_kurtosis_05
1 -0.1049664              0.1175537               0.3292174
  chroma_cens_kurtosis_06 chroma_cens_kurtosis_07 chroma_cens_kurtosis_08
1 -0.4882567              1.734279                1.892659
  chroma_cens_kurtosis_09 ⋯ tonnetz_std_04 tonnetz_std_05 tonnetz_std_06
1 2.28854                 ⋯ 0.06693777     0.02381241     0.02618865
  zcr_kurtosis_01 zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01 zcr_skew_01
1 6.981881        0.140625   0.02654484  0.02197266    0          2.038402
  zcr_std_01
1 0.01952942

In [11]:
# filtrar la especie Eremophila alpestris
sp <- data_summary %>% 
    filter(Especie == "Gymnoderus foetidus")

In [12]:
# Calcular el número de valores nulos por columna
null_counts <- colSums(is.na(sp))

# Filtrar y mostrar solo las columnas que tienen valores nulos
columns_with_nulls <- null_counts[null_counts > 0]
print(columns_with_nulls)

chroma_cens_kurtosis_10 chroma_cens_kurtosis_11 chroma_cens_kurtosis_12
                      1                       1                       1
    chroma_cens_skew_10     chroma_cens_skew_11     chroma_cens_skew_12
                      1                       1                       1

In [13]:
data_final <- data_summary %>% 
    select(-c(names(columns_with_nulls)))

In [14]:
species <- data_final$Especie

In [15]:
data_final$Especie <- gsub(" ", "_", species)

In [16]:
head(data_final,6)

  Especie                  chroma_cens_kurtosis_01 chroma_cens_kurtosis_02
1 Acropternis_orthonyx     1.6035175               1.9254269
2 Agriornis_albicauda      0.8044930               0.1689194
3 Agriornis_montanus       3.1259965               5.9364330
4 Alopochelidon_fucata     0.4226607               0.3066941
5 Amblycercus_holosericeus 0.2142845               0.4114130
6 Ammodramus_aurifrons     2.5038159               1.8160115
  chroma_cens_kurtosis_03 chroma_cens_kurtosis_04 chroma_cens_kurtosis_05
1 2.0113514               0.9679911               1.76944194
2 0.6051555               0.1904388               1.53247590
3 5.6533131               4.0736154               3.57897102
4 0.3579240               0.9576736               0.66702319
5 0.2002995               0.1841674               0.09095704
6 0.5719813               0.8728038               0.48574777
  chroma_cens_kurtosis_06 chroma_cens_kurtosis_07 chroma_cens_kurtosis_08
1  6.0204999               1.9440984               1.4049276
2 13.8752144              13.4608701              13.5067325
3 51.8848434              65.7252112              49.8288544
4  2.5535917              14.6005357               9.8852426
5  0.2686725               0.2038994               0.1390147
6  4.1884804               6.1361146               5.2165309
  chroma_cens_kurtosis_09 ⋯ tonnetz_std_04 tonnetz_std_05 tonnetz_std_06
1  3.698810               ⋯ 0.08159752     0.03028516     0.03343773
2 11.323860               ⋯ 0.05054540     0.02022468     0.02087898
3 27.685244               ⋯ 0.06501535     0.02367763     0.02268967
4  5.031717               ⋯ 0.04889180     0.02007483     0.02148614
5  0.831263               ⋯ 0.07183474     0.03026074     0.02905769
6  4.617376               ⋯ 0.05195927     0.02112090     0.02126104
  zcr_kurtosis_01 zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01 zcr_skew_01
1  7.725479       0.3009133  0.1296930   0.1308894     0.02853644 0.8610324
2  6.001015       0.4113281  0.1702988   0.1711426     0.04782715 0.3262133
3 12.757831       0.3662598  0.1772626   0.1799683     0.04099121 0.2851319
4  4.589060       0.2967936  0.1504630   0.1504313     0.03927409 0.4392728
5  7.620865       0.3014818  0.1337720   0.1304507     0.03787895 0.8371403
6  3.920711       0.3968348  0.2177199   0.2019141     0.05942462 0.5777356
  zcr_std_01
1 0.03859638
2 0.04780803
3 0.03937832
4 0.03528906
5 0.03968411
6 0.06110676

In [18]:
data_final[!complete.cases(data_final),]

Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"
Warning message in cbind(parts$left, chars$ellip_h, parts$right, deparse.level = 0L):
"number of rows of result is not a multiple of vector length (arg 2)"

     Especie chroma_cens_kurtosis_01 chroma_cens_kurtosis_02
     chroma_cens_kurtosis_03 chroma_cens_kurtosis_04 chroma_cens_kurtosis_05
     chroma_cens_kurtosis_06 chroma_cens_kurtosis_07 chroma_cens_kurtosis_08
     chroma_cens_kurtosis_09 ⋯ tonnetz_std_04 tonnetz_std_05 tonnetz_std_06
     zcr_kurtosis_01 zcr_max_01 zcr_mean_01 zcr_median_01 zcr_min_01
     zcr_skew_01 zcr_std_01

In [19]:
dim(data_final)
dim(data_summary)

[1] 992 373

[1] 992 379

In [20]:
#guarda el csv
write.csv(data_final, file = "./data_total/data_specie.csv", row.names = FALSE)